<?xml version="1.0"?>

<!DOCTYPE residueTable [
  <!ELEMENT residueTable (residue)*>
  <!ELEMENT residue (property)*>
  <!ATTLIST residue token ID #IMPLIED>
  <!ELEMENT property (#PCDATA)>

  <!ATTLIST property name CDATA #REQUIRED
                     value CDATA #REQUIRED>

]>

<residueTable>
  <!-- The Residue masses were obtained from Expasy:
  http://www.expasy.ch/tools/findmod/findmod_masses.html 
  The pKa values are from Bjellqvist B. et al., "Reference 
  points for comparisons of two-dimensional maps of proteins from different
  human cell types defined in a pH scale where isoelectric points correlate
  with polypeptide compositions", Electrophoresis 1994, 15, 529-539.-->
  
  <!-- The hydropathicity values are from Kyte J. & Doolittle R.F.
       J. Mol. Biol. 157:105-132(1982). 
    -->
  
  <residue token="A">
    <property name="monoMass" value="71.037114"/>
    <property name="avgMass" value="71.0788"/>
    <property name="pK_Nterm" value="7.59"/>
    <property name="pK" value="0.0"/>
    <property name="pK_Cterm" value="-3.55"/>
    <property name="hydropathicity" value="1.8"/>
  </residue>
  <residue token="C">
    <property name="monoMass" value="103.00919"/>
    <property name="avgMass" value="103.1448"/>
    <property name="pK_Nterm" value="7.50"/>
    <property name="pK" value="-9.0"/>
    <property name="pK_Cterm" value="-3.55"/>
    <property name="hydropathicity" value="2.5"/>  
  </residue>
  <residue token="D">
    <property name="monoMass" value="115.02694"/>
    <property name="avgMass" value="115.0886"/>
    <property name="pK_Nterm" value="7.50"/>
    <property name="pK" value="-4.05"/>
    <property name="pK_Cterm" value="-4.55"/>
    <property name="hydropathicity" value="-3.5"/>  
  </residue>
  <residue token="E">
    <property name="monoMass" value="129.04259"/>
    <property name="avgMass" value="129.1155"/>
    <property name="pK_Nterm" value="7.70"/>
    <property name="pK" value="-4.45"/>
    <property name="pK_Cterm" value="-4.75"/>
    <property name="hydropathicity" value="-3.5"/>
  </residue>
  <residue token="F">
    <property name="monoMass" value="147.06841"/>
    <property name="avgMass" value="147.1766"/>
    <property name="pK_Nterm" value="7.50"/>
    <property name="pK" value="0.0"/>
    <property name="pK_Cterm" value="-3.55"/>
    <property name="hydropathicity" value="2.8"/>
  </residue>
  <residue token="G">
    <property name="monoMass" value="57.021464"/>
    <property name="avgMass" value="57.0520"/>
    <property name="pK_Nterm" value="7.50"/>
    <property name="pK" value="0.0"/>
    <property name="pK_Cterm" value="-3.55"/>
    <property name="hydropathicity" value="-0.4"/> 
  </residue>
  <residue token="H">
    <property name="monoMass" value="137.05891"/>
    <property name="avgMass" value="137.1412"/>
    <property name="pK_Nterm" value="7.50"/>
    <property name="pK" value="5.98"/>
    <property name="pK_Cterm" value="-3.55"/>
    <property name="hydropathicity" value="-3.2"/>
  </residue>
  <residue token="I">
    <property name="monoMass" value="113.08406"/>
    <property name="avgMass" value="113.1595"/>
    <property name="pK_Nterm" value="7.50"/>
    <property name="pK" value="0.0"/>
    <property name="pK_Cterm" value="-3.55"/>
    <property name="hydropathicity" value="4.5"/>
  </residue>
  <residue token="K">
    <property name="monoMass" value="128.09496"/>
    <property name="avgMass" value="128.1742"/>
    <property name="pK_Nterm" value="7.50"/>
    <property name="pK" value="10.00"/>
    <property name="pK_Cterm" value="-3.55"/>
    <property name="hydropathicity" value="-3.9"/>
  </residue>
  <residue token="L">
    <property name="monoMass" value="113.08406"/>
    <property name="avgMass" value="113.1595"/>
    <property name="pK_Nterm" value="7.50"/>
    <property name="pK" value="0.0"/>
    <property name="pK_Cterm" value="-3.55"/>
    <property name="hydropathicity" value="3.8"/>
  </residue>
  <residue token="M">
    <property name="monoMass" value="131.04049"/>
    <property name="avgMass" value="131.1986"/>
    <property name="pK_Nterm" value="7.00"/>
    <property name="pK" value="0.0"/>
    <property name="pK_Cterm" value="-3.55"/>
    <property name="hydropathicity" value="1.9"/>
  </residue>
  <residue token="N">
    <property name="monoMass" value="114.04293"/>
    <property name="avgMass" value="114.1039"/>
    <property name="pK_Nterm" value="7.50"/>
    <property name="pK" value="0.0"/>
    <property name="pK_Cterm" value="-3.55"/>
    <property name="hydropathicity" value="-3.5"/>
  </residue>
  <residue token="P">
    <property name="monoMass" value="97.052764"/>
    <property name="avgMass" value="97.1167"/>
    <property name="pK_Nterm" value="8.36"/>
    <property name="pK" value="0.0"/>
    <property name="pK_Cterm" value="-3.55"/>
    <property name="hydropathicity" value="-1.6"/>
  </residue>
  <residue token="Q">
    <property name="monoMass" value="128.05858"/>
    <property name="avgMass" value="128.1308"/>
    <property name="pK_Nterm" value="7.50"/>
    <property name="pK" value="0.0"/>
    <property name="pK_Cterm" value="-3.55"/>
    <property name="hydropathicity" value="-3.5"/>
  </residue>
  <residue token="R">
    <property name="monoMass" value="156.10111"/>
    <property name="avgMass" value="156.1876"/>
    <property name="pK_Nterm" value="7.50"/>
    <property name="pK" value="12.0"/>
    <property name="pK_Cterm" value="-3.55"/>
    <property name="hydropathicity" value="-4.5"/>
  </residue>
  <residue token="S">
    <property name="monoMass" value="87.032029"/>
    <property name="avgMass" value="87.0782"/>
    <property name="pK_Nterm" value="6.93"/>
    <property name="pK" value="0.0"/>
    <property name="pK_Cterm" value="-3.55"/>
    <property name="hydropathicity" value="-0.8"/>
  </residue>
  <residue token="T">
    <property name="monoMass" value="101.04768"/>
    <property name="avgMass" value="101.1051"/>
    <property name="pK_Nterm" value="6.82"/>
    <property name="pK" value="0.0"/>
    <property name="pK_Cterm" value="-3.55"/>
    <property name="hydropathicity" value="-0.7"/>
  </residue>
  <residue token="V">
    <property name="monoMass" value="99.06814"/>
    <property name="avgMass" value="99.1326"/>
    <property name="pK_Nterm" value="7.44"/>
    <property name="pK" value="0.0"/>
    <property name="pK_Cterm" value="-3.55"/>
    <property name="hydropathicity" value="4.2"/>
  </residue>
  <residue token="W">
    <property name="monoMass" value="186.07931"/>
    <property name="avgMass" value="186.2133"/>
    <property name="pK_Nterm" value="7.50"/>
    <property name="pK" value="0.0"/>
    <property name="pK_Cterm" value="-3.55"/>
    <property name="hydropathicity" value="-0.9"/>
  </residue>
  <residue token="Y">
    <property name="monoMass" value="163.06333"/>
    <property name="avgMass" value="163.1760"/>
    <property name="pK_Nterm" value="7.50"/>
    <property name="pK" value="-10.00"/>
    <property name="pK_Cterm" value="-3.55"/>
    <property name="hydropathicity" value="-1.3"/>
  </residue>
  
</residueTable>